# Generated by Django 5.0.1 on 2025-05-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_music_updated_at_like_playlist_playlistsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio_file',
            field=models.FileField(blank=True, help_text='File mp3 thực tế (nếu có)', null=True, upload_to='music/'),
        ),
        migrations.AddField(
            model_name='music',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Link mp3 hoặc stream nhạc', max_length=500, null=True),
        ),
    ]
