# Generated by Django 5.2.1 on 2025-05-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_albumcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
